### ISSUE TITLE
Research a method to only allow the scraper to save course data

### ISSUE THREAD

**Issue by kerfootj** [VikeLabs/scheduler-back-end#15]
# User Story
As a developer, I want only the scraper to be able to make changes to course data.

# Description
Conduct research to find a method to secure posting to /courses such that only requests made by the scraper will modify data.

# Acceptance Criteria
- [ ] Provide details or links to references on how this could be achieved
- [ ] Create a new ticket for implementing to proposed solution

**Comment by kerfootj** [comment]
Using the host name might be sufficient although not the most secure way.
https://stackoverflow.com/questions/18498726/how-do-i-get-the-domain-originating-the-request-in-express-js

**Comment by Gohsato** [comment]
The scraper now directly uploads course data to mongodb.

Here's the work on the scraper side: https://github.com/VikeLabs/scheduler-scraper/pull/22
This PR removed the post endpoint on the backend: https://github.com/VikeLabs/scheduler-back-end/pull/19
